"""
synthesizer.py - Stage 4: Synthesis (Strategist Agent)

Synthesizes all analyzed articles into a Market Brief.
Uses LLM for narrative generation with heuristic fallback.
"""

import json
import logging
from datetime import datetime

log = logging.getLogger(__name__)


# Strategist Agent prompt template
SYNTHESIZER_PROMPT_TEMPLATE = """You are a Lead Market Strategist analyzing financial news.

Analyze the following articles and generate a comprehensive market brief.

Articles:
{articles}

Return ONLY valid JSON (no markdown, no explanation, no code blocks):
{{
         "summary": "Overall market sentiment and key themes",
         "key_points": ["Point 1", "Point 2", "Point 3"],
         "risk_factors": ["Risk 1", "Risk 2"],
         "outlook": "Bullish/Bearish/Neutral with brief explanation"
}}

Rules:
- Maintain strict factual accuracy - do not hallucinate data.
- Focus on actionable insights for traders/investors.
- Keep summary concise (2-3 sentences).
- List top 3 key points and risk factors.
"""


def _build_articles_text(articles):
    """Format articles for LLM prompt."""
    text = ""
    for i, art in enumerate(articles, 1):
        text += f"Article {i}:\n"
        text += f"  Title: {art.get('title', 'Untitled')}\n"
        text += f"  Sentiment: {art.get('sentiment', 'Unknown')}\n"
        text += f"  Summary: {art.get('summary', 'N/A')}\n"
        text += "\n"
    return text


def synthesize_market_brief(articles):
    """Synthesize all analyzed articles into a Market Brief.
    
    Args:
        articles: List of analyzed article dicts
        
    Returns:
        Synthesized market brief string
    """
    try:
        # Build prompt with articles
        articles_text = _build_articles_text(articles)
        prompt = SYNTHESIZER_PROMPT_TEMPLATE.format(articles=articles_text)
        
        # Call LLM
        from core.ollama_client import ollama_call
        result = ollama_call(prompt, timeout=120)
        
        if result:
            log.info("[MI] Market brief generated by LLM")
            return result
        
        log.warning("[MI] LLM returned empty response, using fallback")
    
    except Exception as e:
        log.error(f"[MI] LLM synthesis failed: {e}", exc_info=True)
        
        # Fallback: generate brief from sentiment distribution
    return _fallback_brief(articles)


def _fallback_brief(articles):
    """Fallback brief generation when LLM is unavailable.
    
    Uses sentiment distribution to generate a simple brief.
    """
    bull = sum(1 for a in articles if a.get("sentiment") == "Bullish")
    bear = sum(1 for a in articles if a.get("sentiment") == "Bearish")
    neu = sum(1 for a in articles if a.get("sentiment") == "Neutral")
    total = len(articles)
    
    date_str = datetime.utcnow().strftime("%Y-%m-%d %H:%M")
    
    brief = f"Market Intelligence Brief - {date_str} SGT\n\n"
    brief += f"Total Articles Analyzed: {total}\n"
    brief += f"Bullish: {bull} | Bearish: {bear} | Neutral: {neu}\n\n"
    
    if bull > bear + 2:
        brief += "Overall sentiment is BULLISH. Market indicators suggest positive momentum."
    elif bear > bull + 2:
        brief += "Overall sentiment is BEARISH. Market indicators suggest caution."
    else:
        brief += "Overall sentiment is NEUTRAL. Mixed signals across market indicators."
    
    log.info(f"[MI] Generated fallback brief: {len(brief)} chars")
    return brief
