#!/usr/bin/env python3
"""Rebuild the signals API section in app.py with correct indentation."""
import sys
import py_compile

PATH = "/Users/nghialam/jarvis-hub/app.py"

# Read current file - corrupted version
with open(PATH, "r") as f:
    content = f.read()

lines = content.split("\n")

# Find where signals section starts
signals_start = None
for i, line in enumerate(lines):
    if "Unified Signals Feed" in line:
        signals_start = i
        break

if not signals_start:
    print("ERROR: No signals section found")
    sys.exit(1)

print(f"Signals section starts at line {signals_start + 1}")

# Build the clean signals section
S = []

def d(line=""):
    S.append(line)

d("# ====================================================================")
d("# Unified Signals Feed - NEW FEATURE (v2.0)")
d("# Merges signals_log and trading_alerts into a single API")
d("# ====================================================================")
d("")
d("")
d('@app.route("/api/signals", methods=["GET"])')
d("def api_get_signals():")
d('    """Get unified signal feed from both tables, merged and deduplicated."""')
d("    if not db:")
d('        return jsonify({"signals": [], "error": "DB not initialized"})')
d("")
d("    try:")
d("         # Optional filters")
d('        signal_filter = request.args.get("signal", "").upper()')
d('        severity_filter = request.args.get("severity", "").upper()')
d('        symbol_filter = request.args.get("symbol", "").upper()')
d('        only_unread = request.args.get("unread", "false").lower() == "true"')
d("")
d("         # Fetch signals from BOTH tables")
d("        all_signals = []")
d('        source_counts = {"signals_log": 0, "trading_alerts": 0}')
d("")
d("        try:")
d("             # Table 1: signals_log (from trading bot)")
d('            rows = db._c().execute("""')
d("                SELECT id, symbol, 'TRADING_BOT' as source, signal_type,")
d("                       CAST(strength AS TEXT) as severity, price, details,")
d("                       detected_at as timestamp, delivered as is_delivered, delivery_channel")
d('                FROM signals_log WHERE 1=1')
d('             """).fetchall()')
d("            for row in rows:")
d("                r = dict(row)")
d("                 # Apply filters")
d('                if signal_filter and r["signal_type"] != signal_filter:')
d("                    continue")
d('                if symbol_filter and r["symbol"] != symbol_filter:')
d("                    continue")
d("                all_signals.append(r)")
d('                source_counts["signals_log"] += 1')
d("        except Exception as e:")
d('            print(f"[SIGNALS] signals_log error: {{e}}")')
d("")
d("        try:")
d("             # Table 2: trading_alerts (from auto-scan engine)")
d('            rows = db._c().execute("""')
d("                SELECT id, symbol, 'AUTO_SCAN' as source, signal_type,")
d('                       severity AS severity,')
d("                       CAST(alert_data->>'price' AS REAL) as price,")
d("                       alert_data,")
d("                       timestamp as detected_at,")
d("                       CASE WHEN status='read' THEN 1 ELSE 0 END as is_delivered,")
d("                       delivery_channel")
d('                FROM trading_alerts')
d('             """).fetchall()')
d("            for row in rows:")
d("                r = dict(row)")
d("                 # Parse JSON alert_data if string")
d('                raw = r.get("alert_data")')
d("                if isinstance(raw, str):")
d("                    try:")
d("                        import json as _json")
d('                        r["alert_parsed"] = _json.loads(raw)')
d("                    except Exception:")
d('                        r["alert_parsed"] = None')
d("                else:")
d('                    r["alert_parsed"] = raw')
d("")
d('                del r["alert_data"]')
d("")
d("                 # Apply filters")
d('                if signal_filter and r["signal_type"] != signal_filter:')
d("                    continue")
d('                if symbol_filter and r["symbol"] != symbol_filter:')
d("                    continue")
d('                if only_unread and r.get("is_delivered"):')
d("                    continue")
d("")
d("                all_signals.append(r)")
d('                source_counts["trading_alerts"] += 1')
d("        except Exception as e:")
d('            print(f"[SIGNALS] trading_alerts error: {{e}}")')
d("")
d("         # Sort by timestamp descending (newest first)")
d('        all_signals.sort(key=lambda x: x.get("timestamp", ""), reverse=True)')
d("")
d("         # Deduplication: keep latest signal per symbol")
d("        best_by_symbol = {}")
d("        neutral_kept = []")
d("        for sig in all_signals:")
d('            sym = sig["symbol"]')
d('            stype = sig.get("signal_type", "NEUTRAL")')
d("")
d('            if stype in ("NEUTRAL", "HOLD"):')
d('                if sym not in [s["symbol"] for s in neutral_kept]:')
d("                    neutral_kept.append(sig)")
d("                continue")
d("")
d("            key = (sym, stype)")
d('            if key not in best_by_symbol or sig.get("timestamp", "") > best_by_symbol[key].get("timestamp", ""):')
d("                if key in best_by_symbol:")
d("                    old = best_by_symbol[sym]")
d('                    if old not in neutral_kept and old["symbol"] not in [s["symbol"] for s in neutral_kept]:')
d("                        neutral_kept.append(old)")
d("                best_by_symbol[key] = sig")
d("")
d("        seen_symbols_neutral = set()")
d("        deduped_neutral = []")
d("        for s in neutral_kept:")
d('            if s["symbol"] not in seen_symbols_neutral:')
d('                seen_symbols_neutral.add(s["symbol"])')
d("                deduped_neutral.append(s)")
d("")
d("        final_signals = list(best_by_symbol.values()) + deduped_neutral")
d("")
d("         return jsonify({")
d('             "signals": final_signals,')
d('             "counts": {"total": len(final_signals), "by_source": source_counts}')
d("         })")
d("    except Exception as e:")
d('        print(f"[SIGNALS] Error: {{e}}")')
d('        return jsonify({"signals": [], "error": str(e)}, 500)')
d("")
d("")

# api_latest_signals function
d('@app.route("/api/signals/latest", methods=["GET"])')
d("def api_latest_signals():")
d('     """Get the N most recent signals for grid overview."""')
d('    limit = min(int(request.args.get("limit", "20")), 100)')
d("    if not db:")
d('        return jsonify({"signals": []})')
d("")
d("    try:")
d("        all_signals = []")
d("")
d("         # From signals_log")
d("        try:")
d('            rows = db._c().execute("""')
d("                SELECT symbol, 'TRADING_BOT', signal_type, CAST(strength AS REAL) as strength,")
d("                       price, details, detected_at, delivered as is_delivered, delivery_channel")
d('                FROM signals_log ORDER BY detected_at DESC LIMIT 50')
d('             """).fetchall()')
d("            for row in rows:")
d("                r = dict(row)")
d('                if isinstance(r.get("details"), str):')
d("                    try:")
d("                        import json as _json")
d('                        r["details_parsed"] = _json.loads(r["details"])')
d("                    except Exception:")
d("                        pass")
d("                all_signals.append(r)")
d("        except Exception:")
d("            pass")
d("")
d("         # From trading_alerts")
d("        try:")
d('            rows = db._c().execute("""')
d("                SELECT symbol, 'AUTO_SCAN', signal_type, severity as strength,")
d("                       CAST(alert_data->>'price' AS REAL) as price,")
d("                       alert_data as details,")
d("                       timestamp as detected_at,")
d("                       CASE WHEN status='read' THEN 1 ELSE 0 END AS is_delivered,")
d("                       delivery_channel")
d('                FROM trading_alerts ORDER BY timestamp DESC LIMIT 50')
d('             """).fetchall()')
d("            for row in rows:")
d("                r = dict(row)")
d('                raw = r.get("details")')
d("                if isinstance(raw, str):")
d("                    try:")
d("                        import json as _json")
d('                        r["details_parsed"] = _json.loads(raw)')
d("                    except Exception:")
d('                        r["details_parsed"] = None')
d("                else:")
d('                    r["details_parsed"] = raw')
d('                del r["details"]')
d("                all_signals.append(r)")
d("        except Exception:")
d("            pass")
d("")
d('        all_signals.sort(key=lambda x: x.get("detected_at", ""), reverse=True)')
d('        return jsonify({"signals": all_signals[:limit]})')
d("    except Exception as e:")
d('        return jsonify({"signals": [], "error": str(e)})')
d("")
d("")

# api_signal_for_symbol function  
d('@app.route("/api/signals/symbol/<symbol>", methods=["GET"])')
d("def api_signal_for_symbol(symbol):")
d('     """Get all signals for a specific symbol full history."""')
d("    if not db:")
d('        return jsonify({"symbol": symbol, "signals": []})')
d("")
d("    symbol = str(symbol).upper().strip()")
d("    signals = []")
d("")
d("     # From signals_log")
d("    try:")
d('        rows = db._c().execute("""')
d("            SELECT symbol, 'TRADING_BOT', signal_type, CAST(strength AS REAL) as strength,")
d("                   price, details, detected_at, delivered as is_delivered, delivery_channel")
d("           FROM signals_log WHERE UPPER(symbol)=UPPER(?) ORDER BY detected_at DESC")
d('        """, (symbol,)).fetchall()')
d("        for row in rows:")
d("            r = dict(row)")
d('            if isinstance(r.get("details"), str):')
d("                try:")
d("                    import json as _json")
d('                    r["details_parsed"] = _json.loads(r["details"])')
d("                except Exception:")
d("                    pass")
d("            signals.append(r)")
d("    except Exception as e:")
d('        print(f"[SIGNALS] signals_log lookup: {{e}} for {{symbol}}")')
d("")
d("     # From trading_alerts")
d("    try:")
d('        rows = db._c().execute("""')
d("            SELECT symbol, 'AUTO_SCAN', signal_type, severity as strength,")
d("                   CAST(alert_data->>'price' AS REAL) as price,")
d("                   alert_data as details,")
d("                   timestamp as detected_at,")
d("                   CASE WHEN status='read' THEN 1 ELSE 0 END AS is_delivered,")
d("                   delivery_channel")
d('           FROM trading_alerts WHERE UPPER(symbol)=UPPER(?) ORDER BY timestamp DESC')
d('        """, (symbol,)).fetchall()')
d("        for row in rows:")
d("            r = dict(row)")
d('            raw = r.get("details")')
d('            if isinstance(raw, str):')
d("                try:")
d("                    import json as _json")
d('                    r["details_parsed"] = _json.loads(raw)')
d("                except Exception:")
d("                    pass")
d("            signals.append(r)")
d("    except Exception as e:")
d('        print(f"[SIGNALS] trading_alerts lookup: {{e}} for {{symbol}}")')
d("")
d('    signals.sort(key=lambda x: (x.get("detected_at", "") or x.get("timestamp", "")), reverse=True)')
d('    return jsonify({"symbol": symbol, "signals": signals})')
d("")
d("")

# api_signal_append function
d('@app.route("/api/signals/add", methods=["POST"])')
d("def api_signal_append():")
d('     """Manual signal entry via dashboard or API."""')
d("    if not db:")
d('        return jsonify({"success": False, "error": "DB not initialized"}), 500')
d("")
d('    data = request.get_json() or {}')
d('    symbol = str(data.get("symbol", "")).strip().upper()')
d('    signal_type = str(data.get("signal", "")).upper()')
d('    strength = float(data.get("strength", 0))')
d("")
d("    if not symbol or len(symbol) < 2:")
d('        return jsonify({"success": False, "error": "Invalid symbol"}), 400')
d('    valid_types = ("BUY", "SELL", "HOLD", "STOP_LOSS", "TAKE_PROFIT", "WATCH", "NEUTRAL")')
d("    if signal_type and signal_type not in valid_types:")
d('        return jsonify({"success": False, "error": "Invalid signal type"}), 400')
d("")
d('    details = {k: v for k, v in data.items() if k not in ("symbol", "signal", "strength")}')
d("")
d("     # Persist to signals_log")
d("    try:")
d("        import json as _json")
d('        db._c().execute("""')
d('            INSERT INTO signals_log (symbol, signal_type, strength, price, details, detected_at)')
d('            VALUES (?, ?, ?, ?, ?, ?)')
d('         """, (symbol, signal_type if signal_type else "NEUTRAL", strength,')
d('             data.get("price"), _json.dumps(details), _utc_now_iso()))')
d("        db._conn.commit()")
d('        print(f"[SIGNALS] Added {{symbol}}: {{signal_type}} ({{strength}})")') 
d('        return jsonify({"success": True})')
d("    except sqlite3.Error as e:")
d('        if "no such table" in str(e):')
d('            return jsonify({"success": False, "error": "signals_log not found"}), 500')
d('        print(f"[SIGNALS] Insert error: {{e}}")')
d('        return jsonify({"success": False, "error": str(e)}), 500')
d("")
d("")

# api_signal_mark_delivered function
d('@app.route("/api/signals/mark-delivered", methods=["POST"])')
d("def api_signal_mark_delivered():")
d('     """Mark signal as delivered for cron delivery."""')
d("    if not db:")
d('        return jsonify({"success": True})')
d("")
d("    try:")
d('        rowcount = db._c().execute("""')
d('            UPDATE signals_log SET delivered=1 WHERE id=? AND is_delivered=0')
d('         """, (request.json.get("id"),)).rowcount if request.json else 0')
d("        db._conn.commit()")
d('        return jsonify({"success": True, "marked": rowcount})')
d("    except Exception as e:")
d('        print(f"[SIGNALS] Mark delivered error: {{e}}")')
d('        return jsonify({"success": False, "error": str(e)})')

print(f"Built {len(S)} lines for signals section")

# Verify indentation levels of key lines
for idx in [0,14,17]:  # Comment header, function def, if not db
    if idx < len(S):
        line = S[idx]
        stripped = line.lstrip()
        spaces = len(line) - len(stripped) if stripped else 0
        print(f"  [{spaces:>2} sp] {stripped[:60]}")

# Find cut points in file
before_section = lines[:signals_start]  
after_position = signals_start + 310   # approximate end of corrupted signals section

for i in range(signals_start + 50, min(len(lines), signals_start + 400)):
    if '"/api/alert-feed/clear"' in lines[i]:
        after_position = i - 2   # Remove trailing blank lines
        print(f"Cut at clear_alert line {i+1}")
        break

# Build new file content
print(f"Before section: {len(before_section)} lines, After section will start from {after_position + 1}")

new_content = "\n\n".join(S) + "\n\n" + "\n".join(lines[after_position:])

with open(PATH, "w") as f:
    f.write(new_content)

print(f"\nWritten {{len(new_content.split(chr(10)))}} lines total (was {{len(lines)}})")

# Verify syntax  
try:
    py_compile.compile(PATH, doraise=True)
    print("OK! Syntax check PASSED!")
except SyntaxError as e:
    print(f"SYNTAX ERROR at line {{e.lineno}}: {{e.msg}}")
    ctx = list(new_content.split("\n"))
    for i in range(max(0, e.lineno-5), min(len(ctx), e.lineno+8)):
        marker = "***" if i+1 == e.lineno else "    "
        print(f"{marker} L{{i+1}}: {{ctx[i][:90]}}")
