#!/usr/bin/python3
# -*- coding: utf-8 -*-
"""jarvis_noon_final.py - Compile and deliver the final noon briefing to Telegram"""
import json, os, time, sys, urllib.request, urllib.error

CHAT_ID = "-1003801745265"
BOT_TOKEN = os.environ.get("JARVIS_BOT_TOKEN", "").strip() or \
            os.environ.get("TELEGRAM_BOT_TOKEN", "").strip() or \
            open(os.path.expanduser("~/.hermes/.jarvis_token_cache")).read().strip()

# The compiled briefing — distilled from all 4 LLM sections into one clean message
briefing = """☕ **JARVIS NOON BRIEFING** — 30/05/2026 (Saturday)

━━━━━━━━━━━━━━━━━━━━━━━

🌍 **GLOBAL MACRO & GEOPOLITICAL**

• **SpaceTech-Defense Convergence**: SpaceX awarded $6.45B in Space Force contracts, with gov deals now = 20% of 2025 revenue — validating defense-backed commercial space as a structural shift [TechCrunch](https://techcrunch.com/2026/05/29/spacex-awarded-6-45b-in-space-force-contracts-ahead-of-ipo/)

• **Digital Sovereignty Rising**: Indian court ruling against Google's ad practices is being leveraged globally to challenge keyword-bidding and data monetization models, signaling broader antitrust enforcement trend [TechCrunch](https://techcrunch.com/2026/05/29/founders-seize-on-indian-court-ruling-to-revive-criticism-of-googles-ad-business/)

• **Energy Inflection Point**: Crude oil posted its steepest monthly decline in 6 years, reflecting shifting global demand forecasts and OPEC+ adjustments [VnExpress Kinh doanh](https://vnexpress.net/gia-dau-co-thang-giam-manh-nhat-6-nam-5079982.html)

• **AI Labor Shift**: Developers increasingly refusing to work without AI tools — a productivity boom that researchers warn may cause long-term technical debt and quality degradation [TechCrunch](https://techcrunch.com/2026/05/29/coders-are-refusing-to-work-without-ai-and-that-could-come-back-to-bite-them/)

📈 **KEY MARKET MOVEMENTS**

• **Aerospace & Defense**: Bullish — defense contracts are de-risking IPO valuations and attracting institutional capital to commercial space equities
• **AI SaaS / Software**: Mixed/Cautious — Adobe's conversational AI agent criticized as a "mediocre design intern," while code-generation dependency raises quality concerns [The Verge](https://www.theverge.com/tech/939686/adobes-conversational-ai-agent-is-a-mediocre-design-intern)
• **Energy**: Bearish — oil's 6-year worst monthly decline pressures traditional energy equities but benefits airlines, logistics, manufacturing (lower input costs)
• **Biotech / Longevity**: Emerging theme — Silicon Valley capital flowing into peptide therapies and performance-enhancing compounds

🤖 **NOTABLE NEWS & HIGHLIGHTS**

• **Embodied AI Data Scaling**: Startup Shift offering *free home cleaning* to record human motion data in NY & London — marking pivot from synthetic/simulated to real-world motion capture for general-purpose domestic robots [The Verge](https://www.theverge.com/ai-artificial-intelligence/940007/ai-companies-will-pay-for-robot-training-data)

• **Silicon Valley's Peptide Obsession**: "Steroid Olympics" coverage reveals perf-enhancing biotech transitioning from niche wellness to investable sector [TechCrunch](https://techcrunch.com/2026/05/29/i-went-to-the-so-called-steroid-olympics-to-understand-why-silicon-valley-is-obsessed-with-peptides/)

• **Vietnam Market**: Oil price drops affect local energy sector; regulatory changes in ad tech may ripple through digital economy [VnExpress Kinh doanh](https://vnexpress.net/gia-dau-co-thang-giam-manh-nhat-6-nam-5079982.html)

💡 **ACTIONABLE SIGNALS**

🔻 **Bearish Energy / Bullish Downstream**: Oil's 6-year worst monthly decline = pressure on traditional energy plays, but *tailwind for airlines, logistics, manufacturing* via lower input costs

⚠️ **Cautious on AI Productivity Multiples**: The quality-vs-speed tradeoff in AI coding/design tools is becoming clear — favor companies with robust AI-audit frameworks and QA processes

🔺 **Bullish Defense & Space Economy**: SpaceX's $6.45B contract validates commercial space transition from speculative → contract-driven; look at launch providers, satellite chains, defense contractors

━━━━━━━━━━━━━━━━━━━━━━━
_Jarvis Intelligence Feed • Generated by local LLM (qwen3.6:35b)_
"""

def send_telegram(text):
    url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
    payload = {"chat_id": CHAT_ID, "text": text, "parse_mode": "Markdown", "disable_web_page_preview": True}
    req_data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(url, data=req_data, headers={"Content-Type": "application/json"})
    try:
        resp = urllib.request.urlopen(req, timeout=15)
        result = json.loads(resp.read())
        msg_id = result.get("result", {}).get("message_id", "?")
        print(f"✅ Telegram message sent (msg_id:{msg_id})")
        return True
    except Exception as e:
        print(f"❌ Telegram send failed: {e}", file=sys.stderr)
        return False

if __name__ == "__main__":
    print("Delivering Jarvis Noon Briefing to Telegram...")
    if send_telegram(briefing):
        print("Briefing delivered successfully!")
    else:
        # Fallback: output to stdout so cron can capture it
        print("\n--- FALLBACK OUTPUT ---\n")
        print("ERROR: Telegram delivery failed\n" + briefing)
